from .prompter_multi_agents_pair_image_input import TaskPrompterPairImageInput, LLMQuestionToVLMPairImageInput, VLMAnswerToLLMPairImageInput
from .prompter_vlm_only_pair_image_input import TaskPrompterVLMOnly
